import React, { Component } from 'react'
import './Work.scss'
import Slider from 'react-slick'

class Work extends Component {
    render() {
        var settings = {
            arrows: true,
            infinite: true,
            fade: true,
            speed: 500,
            slidesToShow: 1,
            slidesToScroll: 1
        }
        return (
            <div className="work">
                <div className="work-example">
                    <Slider {...settings}>
                        <div><img src={require('../../img/shopify-challenge/shopify-api.png')} alt="Shopify Challenge API"></img></div>
                        <div><img src={require('../../img/shopify-challenge/get-products.png')} alt="Get Products"></img></div>
                        <div><img src={require('../../img/shopify-challenge/available-products.png')} alt="Available Products"></img></div>
                        <div><img src={require('../../img/shopify-challenge/purchase-product.png')} alt="Purchase Products"></img></div>
                    </Slider>
                    <a href="https://dylan-roberts-shopify.herokuapp.com/" target="_blank" rel="noopener noreferrer"><h2>Shopify Developer Challenge - Summer 2018</h2></a>
                    <p>"Task: Build the barebones of an online marketplace."
                        <br></br><br />
                        A simple marketplace API created using Node.js with Express and a MongoDB Database hosted on mLab. Documented with Swagger.
                    </p>
                    <div className="work-example-links">
                        <a href="https://dylan-roberts-shopify.herokuapp.com/" target="_blank" rel="noopener noreferrer">visit site</a>
                        <a href="https://github.com/americansteel/droberts-shopify-dev-challenge" target="_blank" rel="noopener noreferrer" >repo</a>
                    </div>
                </div>
                <div className="work-example">
                    <Slider {...settings}>
                        <div><img src={require('../../img/blvd/blvd-contact.png')} alt="BLVD MTL Contact "></img></div>
                        <div><img src={require('../../img/blvd/blvd-gallery.png')} alt="BLVD MTL Grid Gallery"></img></div>
                        <div><img src={require('../../img/blvd/blvd-modal.png')} alt="BLVD MTL Image Viewer"></img></div>
                    </Slider>
                    <a href="http://blvd-mtl.com" target="_blank" rel="noopener noreferrer"><h2>BLVD MTL</h2></a>
                    <p>Front end developer on a React application serving content stored in Contentful. </p>
                    <div className="work-example-links">
                        <a href="http://blvd-mtl.com" target="_blank" rel="noopener noreferrer">visit site</a>
                    </div>
                </div>
                <div className="work-example">
                    <Slider {...settings}>
                        <div><img src={require('../../img/dabacana/dabacana-main.png')} alt="Dabacana Main Page"></img></div>
                        <div><img src={require('../../img/dabacana/dabacana-tablet.png')} alt="Dabacana Tablet"></img></div>
                        <div><img src={require('../../img/dabacana/dabacana-mobile.png')} alt="Dabacana Shop Mobile"></img></div>
                    </Slider>
                    <a href="http://staging.dabacana.com" target="_blank" rel="noopener noreferrer"><h2>Dabacana</h2></a>
                    <p>A single page application/blog built in React, generated by Gatsby and Wordpress for CMS.</p>
                    <div className="work-example-links">
                        <a href="http://staging.dabacana.com" target="_blank" rel="noopener noreferrer">visit site</a>
                    </div>
                </div>
                <div className="work-example">
                    <Slider {...settings}>
                        <div><img src={require('../../img/breadmin/breadmin-dashboard.png')} alt="Breadmin Dashboard"></img></div>
                        <div><img src={require('../../img/breadmin/breadmin-dashboard-mobile.png')} alt="Breadmin Mobile Dashboard"></img></div>
                        <div><img src={require('../../img/breadmin/breadmin-products.png')} alt="Breadmin Products"></img></div>
                        <div><img src={require('../../img/breadmin/breadmin-users-mobile.png')} alt="Breadmin Users Mobile"></img></div>
                    </Slider>
                    <a href="http://breadmin.herokuapp.com" target="_blank" rel="noopener noreferrer"><h2>Breadmin</h2></a>
                    <p>Breadmin is a bakery management management application with a RESTful API
                    my team and I created using Angular, Express, Node, and MongoDB. We worked with Forno Cultura, a
                    local bakery to create an application that suited their needs</p>
                    <div className="work-example-links">
                        <a href="http://breadmin.herokuapp.com" target="_blank" rel="noopener noreferrer">visit site</a>
                    </div>
                </div>
            </div>
        )
    }
}

export default Work